### ISSUE TITLE
Issue programming the GAL

### ISSUE THREAD

**Issue by Parakas82** [chris-jh/MegaCD-Connect-BD-Remake#2]
Hi there,

Thanks for your projects, I am big fan! I am trying to reconstruct two JAP MCD1 units that had really bad PCBs, and they are coming back to life thanks to you.

Unfortunately I got stuck in the last bit, programming the GALs.
I got some (5X) GAL22V10B-15PC, and I am trying to program them with my T48 programmer, I load the JED file , and everything seems in order, but I get the following error when I try:

APP Version : 12.66   Model : T48
     Device : GAL22V10B
Pins Detected Passed!
Erase Chip....Timer : 828ms
Programing Fuse Bits completed ....Timer :4750 ms
Verify Error!    FUSE bit:0     Buff_val: 0     IC_val: 1
Programming Stopped!

And then I see that the GAL has only 1´s in it, so the process did nothing in the end.

I have tried different VPP voltages, enabling and disabling the ¨Encrypt Chip¨ flag, different IC models.... I run out of ideas to be honest. Apologies in advance if this is not the right place to ask something like this, I am not familiar using GitHub.
Thank you in advance for your time,

Regards.

**Comment by chris-jh** [comment]
Where did you get the GAL's from ?

**Comment by Parakas82** [comment]
Hi, Aliexpress 🙃 Got any good recommendation where should I source them at a reasonable price?

Thanks for the help!

**Comment by chris-jh** [comment]
ah, yeah will be hit or miss with Ali, i had some that worked fine and some others that programmed no errors, but didn't worked also.

Ones i got from eBay also worked, but probably same in getting genuine or fakes.

The mouser ATF22V10C-15PU as an alternative, at least with them should be real.

or try your luck on Ali/Ebay maybe they don't fake them as much ?? 😂

**Comment by BBZ149** [comment]
Hi Chris, would pic of attached GAL work OK?

Thanks
Terry
![GAL22V10D](https://github.com/Board-Folk/MegaCD-Connect-BD-Remake/assets/161533756/067ae07d-7f74-4482-9d55-97b7b34b8303)

**Comment by chris-jh** [comment]
Looks ok, but looks can be deceiving😄, try it and see.

It will either programme and work, or programme and black screen, or not programme.

**Comment by BBZ149** [comment]
That's true! lol but going by the model of the Chip is that the correct one? As I have to buy 15 and not cheap 😞 But they are 100% genuine!

**Comment by chris-jh** [comment]
I am unsure i have only used the chips marked as GAL22V10B-15LP or ATF22V10B-15PC.

**Comment by Parakas82** [comment]
Hi Chris,

Following your advice, I got some ATF22V10C-15PU on their way:
https://www.rs-online-privat.de/Products/ProductDetail/Microchip-SPLD-Simple-Programmable-Logic-Device-ATF22V10C-350-Gates-10-Makrozellen-10-I-O-83-3MHz-15ns-CMOS-TTL-1278214

Hopefully they will do the job, thanks for the help!

Regards.

**Comment by chris-jh** [comment]
> Hi Chris,
> 
> Following your advice, I got some ATF22V10C-15PU on their way: https://www.rs-online-privat.de/Products/ProductDetail/Microchip-SPLD-Simple-Programmable-Logic-Device-ATF22V10C-350-Gates-10-Makrozellen-10-I-O-83-3MHz-15ns-CMOS-TTL-1278214
> 
> Hopefully they will do the job, thanks for the help!
> 
> Regards.

Did they work ?

**Comment by Parakas82** [comment]
Hey Chris,

Experienced a bit of a nightmare with the delivery, but got them finally: they erased/programmed straight away. They are on their way to my colleague via post, to be tested with my two MCDs to be resurrected :) I'll let you know how it went.

Regards.

**Comment by LobAnovich** [comment]
Greetings !  If using ATF22V10B-15PC, should I use the .jed firmware file from GAL22V10?

**Comment by Parakas82** [comment]
> Greetings !  If using ATF22V10B-15PC, should I use the .jed firmware file from GAL22V10?

Hi yes! Mines are going to be tested soon, I'll let you know how it went.

**Comment by chris-jh** [comment]
yeah use the GAL22V10 jed as the ATF22V10B in the minipro if you are using that to program

**Comment by LobAnovich** [comment]
Is it possible to replace CD74ACT10E with 74HC10?

**Comment by Parakas82** [comment]
Confirmed, they work!!

**Comment by LobAnovich** [comment]
Greetings !  I received 2 + 2 GAL22V10B chips from Ali from different sellers.  The chips are erased, programmed, but do not pass verification unless the “verification after recording” checkbox is unchecked.  Is it possible that this is a “lock bit” action and for the same reason it is impossible to remove a dump from the original chip or are these still fake chips?  Do I need to leave the “lock bit” and “encrypt chip” checkboxes before recording?  Programmer TL866II-Plus.  Xgpro 12.66 program
